SDTM_DM_REQUIRED = {"STUDYID", "USUBJID", "SUBJID", "DOMAIN"}
SDTM_AE_REQUIRED = {"STUDYID", "USUBJID", "AESEQ", "AETERM", "AESTDTC"}
ADAM_ADSL_REQUIRED = {"STUDYID", "USUBJID", "TRT01A", "SAFFL"}
ADAM_ADAE_REQUIRED = {"STUDYID", "USUBJID", "AESEQ", "TRTA", "SAFFL"}

